from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BrowserClient(Protocol):
    def navigate(self, url: str) -> None: ...

    def snapshot(self) -> str: ...

    def click(self, ref_or_selector: str) -> None: ...

    def fill(self, ref_or_selector: str, text: str) -> None: ...

    def evaluate(self, js: str) -> Any: ...

    def screenshot(self) -> bytes: ...

    def wait_ms(self, ms: int) -> None: ...
